"""nullable password

Revision ID: 792b8653dfbc
Revises: 84bec662d235
Create Date: 2025-03-25 09:51:53.974113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792b8653dfbc'
down_revision = '84bec662d235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
