"""add capacity

Revision ID: d3fe31b8555b
Revises: aadec58f6839
Create Date: 2025-03-23 11:41:25.811996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fe31b8555b'
down_revision = 'aadec58f6839'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('events') as batch_op:
        batch_op.add_column(sa.Column('event_capacity', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('event_capacity')

    # ### end Alembic commands ###
